# Generated by Django 3.0.6 on 2020-09-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paymentmethod',
            field=models.CharField(default='ondelivery', max_length=30),
        ),
    ]
