# Generated by Django 3.1.2 on 2020-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201010_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paymentref',
            field=models.CharField(default='noref', max_length=50),
        ),
    ]
