# Generated by Django 3.1.2 on 2020-12-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_cart_paymentref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='picture1',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='picture2',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='picture3',
            field=models.FileField(upload_to='media'),
        ),
    ]
